apiVersion: v1
kind: Pod
metadata:
  name: yaml-applier
  namespace: wordpress
  labels:
    app: app-yamls
spec:
  containers:
  - name: yaml-applier
    image: bitnami/kubectl:latest
    command: ["/bin/sh","-c"]
    args: 
    - kubectl apply -f /yaml/manifests.yaml && tail -f /dev/null
    volumeMounts:
    - mountPath: /yaml
      name: yamls
    securityContext:
      runAsUser: 0
  volumes:
  - name: yamls
    persistentVolumeClaim:
      claimName: yaml-pv-claim
  imagePullSecrets:
  - name: my-registry-secret
  