apiVersion: v1
kind: Pod
metadata:
  name: yaml-getter
  namespace: wordpress
  labels:
    app: app-yamls
spec:
  containers:
  - name: yaml-getter
    image: bitnami/kubectl:latest
    command: ["/bin/sh","-c","tail -f /dev/null"]
##    args: 
##    - kubectl get svc,secrets,deployments -n wordpress -l app=wordpress -o yaml > /yaml/manifests.yaml && tail -f /dev/null
    volumeMounts:
    - mountPath: /yaml
      name: yamls
    securityContext:
      runAsUser: 0
  volumes:
  - name: yamls
    persistentVolumeClaim:
      claimName: yaml-pv-claim
  imagePullSecrets:
  - name: my-registry-secret
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: yaml-pv-claim
#   namespace: wordpress
#   labels:
#     app: app-yamls
# spec:
#   storageClassName: default-storageclass
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: app-config-job
#   namespace: wordpress
# spec:
#   completions: 1
#   template:
#     metadata:
#       name: yaml-getter
#       namespace: wordpress
#       labels:
#         app: app-yamls
#     spec:
#       containers:
#       - name: yaml-getter
#         image: bitnami/kubectl:latest
#         command: ["/bin/sh","-c"]
#         args: 
#         - kubectl get svc,secrets,deployments -n wordpress -l app=wordpress -o yaml > /yaml/manifests.yaml 
#         volumeMounts:
#         - mountPath: /yaml
#           name: yamls
#         securityContext:
#           runAsUser: 0
#       volumes:
#       - name: yamls
#         persistentVolumeClaim:
#           claimName: yaml-pv-claim
#       imagePullSecrets:
#       - name: my-registry-secret  
#       restartPolicy: OnFailure
  