apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podpvss
  namespace: wordpress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podpvss
subjects:
- kind: ServiceAccount
  name: default
  namespace: wordpress
