apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: podpvss
  namespace: wordpress
rules:
- apiGroups: ["apps"]
  resources:
  - deployments
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create
- apiGroups: [""]
  resources:
  - pods
  - persistentvolumeclaims
  - persistentvolumes
  - secrets
  - deployments
  - services
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create
- apiGroups: ["batch"]
  resources:
  - jobs
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create
- apiGroups: ["snapshot.storage.k8s.io"]
  resources:
  - volumesnapshots
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create
