apiVersion: snapshot.storage.k8s.io/v1
deletionPolicy: Delete
driver: csi.nutanix.com
kind: VolumeSnapshotClass
metadata:
  name: default-snapshotclass
parameters:
  csi.storage.k8s.io/snapshotter-secret-name: ntnx-secret-00061b3a-5a4d-5b42-0000-000000029842
  csi.storage.k8s.io/snapshotter-secret-namespace: kube-system
  storageType: NutanixVolumes
